package com.qt.qtBackend.mapper;

import com.qt.qtBackend.auth.dto.AlumnoAuthResponse;
import com.qt.qtBackend.auth.dto.DocenteAuthResponse;
import com.qt.qtBackend.auth.dto.InstitucionAuthResponse;
import com.qt.qtBackend.dto.agente.HistorialItemDto;
import com.qt.qtBackend.dto.alumno.AlumnoAllResponse;
import com.qt.qtBackend.dto.alumnoInstitucion.AInstitucionAllResponse;
import com.qt.qtBackend.dto.alumnoInstitucion.AlumnoIAllResponse;
import com.qt.qtBackend.dto.alumnoInstitucion.AlumnoInstitucionAllResponse;
import com.qt.qtBackend.dto.asignacion.AsignacionAllResponse;
import com.qt.qtBackend.dto.asignacion.AsignacionEvidenciaResponse;
import com.qt.qtBackend.dto.asignacion.AsignacionFilterAShortResponse;
import com.qt.qtBackend.dto.asignatura.AsignaturaAllResponse;
import com.qt.qtBackend.dto.conversacion.ConversacionAllResponse;
import com.qt.qtBackend.dto.conversacion.ConversacionShortResponse;
import com.qt.qtBackend.dto.docente.DocenteAllResponse;
import com.qt.qtBackend.dto.docenteInstitucion.DInstitucionAllResponse;
import com.qt.qtBackend.dto.docenteInstitucion.DocenteIAllResponse;
import com.qt.qtBackend.dto.docenteInstitucion.DocenteInstitucionAllResponse;
import com.qt.qtBackend.dto.institucion.InstitucionAllResponse;
import com.qt.qtBackend.dto.materialAcademico.MaterialAcademicoAllResponse;
import com.qt.qtBackend.dto.materialAcademico.MaterialAcademicoShortResponse;
import com.qt.qtBackend.dto.matricula.MatriculaAllResponse;
import com.qt.qtBackend.dto.matricula.MatriculaShortResponse;
import com.qt.qtBackend.dto.mensaje.MensajeShortResponse;
import com.qt.qtBackend.dto.mision.MisionAllResponse;
import com.qt.qtBackend.dto.mision.MisionIAllResponse;
import com.qt.qtBackend.dto.misionAsignatura.MAsignaturaShortResponse;
import com.qt.qtBackend.dto.misionAsignatura.MisionAsignaturaShortResponse;
import com.qt.qtBackend.dto.unidad.UnidadAllResponse;
import com.qt.qtBackend.dto.unidad.UnidadShortResponse;
import com.qt.qtBackend.dto.unidadAsignatura.UnidadAsignaturaAllResponse;
import com.qt.qtBackend.dto.resultado.ResultadoAllResponse;
import com.qt.qtBackend.dto.rol.RolAllResponse;
import com.qt.qtBackend.dto.unidadAsignatura.UnidadAsignaturaShortResponse;
import com.qt.qtBackend.dto.usuario.UsuarioAllResponse;
import com.qt.qtBackend.model.*;

public interface IMapperService {
    RolAllResponse convRolAll(Rol obj);
    UsuarioAllResponse convUsuarioAll(Usuario obj);
    InstitucionAllResponse convInstitucionAll(Institucion obj);
    InstitucionAuthResponse convInstitucionAuth(Institucion obj);
    DocenteAllResponse convDocenteAll(Docente obj);
    DocenteAuthResponse convDocenteAuth(Docente obj);
    AsignaturaAllResponse convAsignaturaAll(Asignatura obj);
    DocenteInstitucionAllResponse convDocenteInstitucionAll(DocenteInstitucion obj);
    DInstitucionAllResponse convDInstitucionAll(DocenteInstitucion obj);
    DocenteIAllResponse convDocenteIAll(DocenteInstitucion obj);
    AlumnoAllResponse convAlumnoAll(Alumno obj);
    AlumnoAuthResponse convAlumnoAuth(Alumno obj);
    AlumnoInstitucionAllResponse convAlumnoInstitucionAll(AlumnoInstitucion obj);
    AInstitucionAllResponse convAInstitucionAll(AlumnoInstitucion obj);
    AlumnoIAllResponse convAlumnoIAll(AlumnoInstitucion obj);
    MisionAllResponse convMisionAll(Mision obj);
    MisionIAllResponse convMisionIAll(Mision obj);
    ConversacionAllResponse convConversacionAll(Conversacion obj);
    ConversacionShortResponse convConversacionShort(Conversacion obj);
    MensajeShortResponse convMensajeShort(Mensaje obj);
    MisionAsignaturaShortResponse convMisionAsignaturaShort(MisionAsignatura obj);
    MAsignaturaShortResponse convMAsignaturaShort(MisionAsignatura obj);
    AsignacionAllResponse convAsignacionAll(Asignacion obj);
    AsignacionEvidenciaResponse convAsignacionEvidencia(Asignacion obj);
    AsignacionFilterAShortResponse convAsignacionFilterAShort(Asignacion obj);
    MatriculaAllResponse convMatriculaAll(Matricula obj);
    MatriculaShortResponse convMatriculaShort(Matricula obj);
    ResultadoAllResponse convResultadoAll(Resultado obj);
    UnidadAllResponse convUnidadAll(Unidad obj);
    UnidadShortResponse convUnidadShort(Unidad obj);
    UnidadAsignaturaAllResponse convUnidadAsignaturaAll(UnidadAsignatura obj);
    UnidadAsignaturaShortResponse convUnidadAsignaturaShort(UnidadAsignatura obj);
    MaterialAcademicoAllResponse convMaterialAcademicoAll(MaterialAcademico obj);
    MaterialAcademicoShortResponse convMaterialAcademicoShort(MaterialAcademico obj);
    HistorialItemDto convHistorialItem(MensajeShortResponse obj);
}
